spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        search:
          default:
            directory_provider: "filesystem"
            indexBase: "/var/lucene/indexes"
  profiles:
    active: daoproduct

server:
  port: 9090

