spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        search:
          lucene_version: "5.5.5"
          default:
            directory_provider: "local-heap"
  profiles:
    active: dao

server:
  servlet:
    context-path: "/api"

rmi:
  host: "127.0.0.1"
  port: "9911"


################ 消息配置 ################
global-msg:
  internal-error: "内部错误"

paper-msg:
  mismatch-id: "找不到ID所对应的论文"

rank-msg:
  each-num: 10
  mismatch-page-number: "查询的页号与结果数量不匹配"

security-msg:
  need-authorities: "Need Authorities!"
  login-failure: "Login Failure!"
  login-success: "Login Success!"
  logout-success: "Logout Success!"
  no-such-user: "Account Not Exist!"

entity-msg:
  author-type: 1
  affiliation-type: 2
  conference-type: 3
  term-type: 4
  paper-type: 5

