spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        search:
          default:
            directory_provider: "filesystem"
            indexBase: "/var/lucene/indexes"
  profiles:
    include: daoproduct

server:
  port: 9090

