spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        search:
          lucene_version: "5.5.5"
          analyzer: "noStopWords"
          default:
            directory_provider: "local-heap"
    hibernate:
      ddl-auto: create

server:
  servlet:
    context-path: "/api"


################ 消息配置 ################
global-msg:
  internal-error: "内部错误"

paper-msg:
  mismatch-id: "找不到ID所对应的论文"

rank-msg:
  each-num: 10
  mismatch-page-number: "查询的页号与结果数量不匹配"

security-msg:
  need-authorities: "Need Authorities!"
  login-failure: "Login Failure!"
  login-success: "Login Success!"
  logout-success: "Logout Success!"
  no-such-user: "Account Not Exist!"

entity-msg:
  author-type: 1
  affiliation-type: 2
  conference-type: 3
  term-type: 4
  paper-type: 5

parse-csv:
  need: true
