spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        search:
          default:
            directory_provider: "local-heap"

server:
  servlet:
    context-path: "/api"


################ 消息配置 ################
global-msg:
  internal-error: "内部错误"

paper-msg:
  mismatch-id: "找不到ID所对应的论文"

rank-msg:
  each-num: 10
  mismatch-page-number: "查询的页号与结果数量不匹配"

security-msg:
  need-authorities: "Need Authorities!"
  login-failure: "Login Failure!"
  login-success: "Login Success!"
  logout-success: "Logout Success!"
  no-such-user: "Account Not Exist!"
parse-csv:
  need: true