spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        search:
          default:
            directory_provider: "local-heap"
      hbm2ddl:
        import_files: "classpath:import.sql"
    hibernate:
      ddl-auto: create
