spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
        search:
          default:
            directory_provider: "local-heap"
    hibernate:
      ddl-auto: update


################ 消息配置 ################
global-msg:
  internal-error: "内部错误"

paper-msg:
  mismatch-id: "找不到ID所对应的论文"
