spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: edu.nju.se.teamnamecannotbeempty.backend.config.MyDialect
        show_sql: false
        format_sql: false
        search:
          analyzer: "noStopWords"
          default:
            directory_provider: "local-heap"
    hibernate:
      ddl-auto: create


################ 消息配置 ################
global-msg:
  internal-error: "内部错误"

paper-msg:
  mismatch-id: "找不到ID所对应的论文"

rank-msg:
  each-num: 10
  mismatch-page-number: "查询的页号与结果数量不匹配"